In [2]:
import pandas as pd
import numpy as np

In [3]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0] = None

In [7]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [8]:
from numpy import nan as NA

In [9]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data = pd.DataFrame([[1., 6.5, 3,], [1, NA, NA],
                    [NA, NA, NA], [NA, 6.5, 3]])

In [13]:
cleaned = data.dropna()

In [14]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [16]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [17]:
data[4] = NA

In [18]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [21]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [22]:
df = pd.DataFrame(np.random.randn(7, 3))

In [23]:
df.iloc[:4, 1] = NA

In [24]:
df.iloc[:2, 2] = NA

In [25]:
df

0         1         2
0  0.414959       NaN       NaN
1  0.303657       NaN       NaN
2  0.810118       NaN -0.767482
3 -0.817074       NaN  1.104013
4 -0.506823 -0.754917 -0.547951
5  2.176640  0.500492  0.249381
6 -0.369761 -0.345379  1.750427

In [26]:
df.dropna()

0         1         2
4 -0.506823 -0.754917 -0.547951
5  2.176640  0.500492  0.249381
6 -0.369761 -0.345379  1.750427

In [27]:
df.dropna(thresh=2)

0         1         2
2  0.810118       NaN -0.767482
3 -0.817074       NaN  1.104013
4 -0.506823 -0.754917 -0.547951
5  2.176640  0.500492  0.249381
6 -0.369761 -0.345379  1.750427

In [28]:
df.fillna(0)

0         1         2
0  0.414959  0.000000  0.000000
1  0.303657  0.000000  0.000000
2  0.810118  0.000000 -0.767482
3 -0.817074  0.000000  1.104013
4 -0.506823 -0.754917 -0.547951
5  2.176640  0.500492  0.249381
6 -0.369761 -0.345379  1.750427

In [30]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.414959  0.500000  0.000000
1  0.303657  0.500000  0.000000
2  0.810118  0.500000 -0.767482
3 -0.817074  0.500000  1.104013
4 -0.506823 -0.754917 -0.547951
5  2.176640  0.500492  0.249381
6 -0.369761 -0.345379  1.750427

In [31]:
_ = df.fillna(0, inplace=True)

In [32]:
df

0         1         2
0  0.414959  0.000000  0.000000
1  0.303657  0.000000  0.000000
2  0.810118  0.000000 -0.767482
3 -0.817074  0.000000  1.104013
4 -0.506823 -0.754917 -0.547951
5  2.176640  0.500492  0.249381
6 -0.369761 -0.345379  1.750427

In [33]:
df = pd.DataFrame(np.random.randn(6, 3))

In [34]:
df.iloc[2:, 1] = NA

In [35]:
df.iloc[4:, 2] = NA

In [36]:
df

0         1         2
0 -0.341281 -0.979827  0.550388
1 -1.497251  0.909381 -0.864797
2  0.312333       NaN -1.990113
3  0.410831       NaN  0.622230
4 -0.204456       NaN       NaN
5 -0.588208       NaN       NaN

In [37]:
df.fillna(method='ffill')

0         1         2
0 -0.341281 -0.979827  0.550388
1 -1.497251  0.909381 -0.864797
2  0.312333  0.909381 -1.990113
3  0.410831  0.909381  0.622230
4 -0.204456  0.909381  0.622230
5 -0.588208  0.909381  0.622230

In [38]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -0.341281 -0.979827  0.550388
1 -1.497251  0.909381 -0.864797
2  0.312333  0.909381 -1.990113
3  0.410831  0.909381  0.622230
4 -0.204456       NaN  0.622230
5 -0.588208       NaN  0.622230

In [39]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [40]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [43]:
data = pd.DataFrame({'k1' : ['one', 'two'] * 3 + ['two'],
                    'k2': [1, 1, 2, 3, 3, 4, 4]})

In [44]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [45]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [46]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [47]:
data['v1'] = range(7)

In [48]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [49]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [50]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
                    'Pastrami', 'corned beef', 'Bacon',
                    'pastrami', 'honey ham', 'nova lox'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [51]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [57]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [54]:
lowercased = data['food'].str.lower()

In [55]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [58]:
data['animal'] = lowercased.map(meat_to_animal)

In [59]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [61]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [62]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [63]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [64]:
data.replace(-999, NA)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [65]:
data.replace([-999, -1000], NA)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [66]:
data.replace([-999, -1000], [NA, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [67]:
data.replace({-999: NA, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [68]:
data = pd.DataFrame(np.arange(12).reshape(3, 4),
                   index=['Ohio', 'Colorado', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [69]:
transform = lambda x: x[:4].upper()

In [70]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [71]:
data.index = data.index.map(transform)

In [72]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [73]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [74]:
data.rename(index={'OHIO': 'INDIANA'},
           columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [75]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [76]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [77]:
ages = [20, 22, 25 ,27, 21, 23, 37, 31, 61, 45, 41, 32]

In [78]:
bins = [18, 25, 35, 60, 100]

In [80]:
cats = pd.cut(ages, bins)

In [81]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [82]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [83]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [84]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [86]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [87]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [88]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [89]:
data = np.random.rand(20)

In [90]:
pd.cut(data, 4, precision=2)

[(0.68, 0.89], (0.03, 0.25], (0.03, 0.25], (0.68, 0.89], (0.68, 0.89], ..., (0.68, 0.89], (0.03, 0.25], (0.68, 0.89], (0.25, 0.46], (0.68, 0.89]]
Length: 20
Categories (4, interval[float64]): [(0.03, 0.25] < (0.25, 0.46] < (0.46, 0.68] < (0.68, 0.89]]

In [91]:
data = np.random.randn(1000)

In [92]:
cats = pd.qcut(data, 4)

In [93]:
cats

[(0.616, 3.318], (-3.0589999999999997, -0.703], (0.616, 3.318], (0.616, 3.318], (-0.0574, 0.616], ..., (-0.703, -0.0574], (-0.703, -0.0574], (-0.0574, 0.616], (-0.703, -0.0574], (-0.703, -0.0574]]
Length: 1000
Categories (4, interval[float64]): [(-3.0589999999999997, -0.703] < (-0.703, -0.0574] < (-0.0574, 0.616] < (0.616, 3.318]]

In [94]:
pd.value_counts(cats)

(0.616, 3.318]                   250
(-0.0574, 0.616]                 250
(-0.703, -0.0574]                250
(-3.0589999999999997, -0.703]    250
dtype: int64

In [95]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(1.274, 3.318], (-1.283, -0.0574], (1.274, 3.318], (-0.0574, 1.274], (-0.0574, 1.274], ..., (-1.283, -0.0574], (-1.283, -0.0574], (-0.0574, 1.274], (-1.283, -0.0574], (-1.283, -0.0574]]
Length: 1000
Categories (4, interval[float64]): [(-3.0589999999999997, -1.283] < (-1.283, -0.0574] < (-0.0574, 1.274] < (1.274, 3.318]]

In [96]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [97]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.030863    -0.019093    -0.016352     0.003258
std       0.990896     0.985869     1.013790     0.977484
min      -3.157924    -3.242982    -3.840046    -3.258174
25%      -0.608481    -0.678411    -0.712953    -0.675895
50%       0.060618    -0.002107    -0.024527     0.035332
75%       0.654073     0.643227     0.652382     0.684863
max       2.886382     3.213407     3.100541     2.934137

In [98]:
col = data[2]

In [99]:
col[np.abs(col) > 3]

237    3.100541
889   -3.840046
977    3.011491
Name: 2, dtype: float64

In [100]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
108 -0.940349 -3.064471 -0.059850  0.366119
170 -0.152121  3.213407  1.381971  0.147385
233  1.046858 -0.553117 -0.864375 -3.258174
237  0.136958  0.741062  3.100541  0.518526
248  0.535583 -3.202982 -0.038058  0.021920
506 -3.157924 -0.329709  0.619580 -1.914649
784 -0.086620 -3.037784 -0.297340  1.479077
886  0.179533 -3.242982 -0.534724 -0.791070
889 -1.000083  0.138351 -3.840046  0.004909
977 -0.678610 -1.713857  3.011491  0.070847

In [101]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [102]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.031021    -0.018758    -0.015624     0.003516
std       0.990400     0.983476     1.010623     0.976656
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.608481    -0.678411    -0.712953    -0.675895
50%       0.060618    -0.002107    -0.024527     0.035332
75%       0.654073     0.643227     0.652382     0.684863
max       2.886382     3.000000     3.000000     2.934137

In [103]:
np.sign(data).head()

0    1    2    3
0  1.0 -1.0 -1.0 -1.0
1  1.0 -1.0 -1.0 -1.0
2  1.0 -1.0 -1.0  1.0
3  1.0 -1.0  1.0  1.0
4 -1.0 -1.0 -1.0  1.0

In [104]:
df = pd.DataFrame(np.arange(5 * 4).reshape(5, 4))

In [105]:
sampler = np.random.permutation(5)

In [106]:
sampler

array([1, 0, 3, 2, 4])

In [107]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [108]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11
4  16  17  18  19

In [109]:
df.sample(n=3)

0   1   2   3
2   8   9  10  11
4  16  17  18  19
1   4   5   6   7

In [110]:
choices = pd.Series([5, 7, -1, 6, 4])

In [111]:
draws = choices.sample(n=10, replace=True)

In [112]:
draws

3    6
0    5
4    4
1    7
3    6
3    6
3    6
4    4
2   -1
3    6
dtype: int64

In [113]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                  'data1': range(6)})

In [114]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [115]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [117]:
df_with_dummy = df[['data1']].join(dummies)

In [118]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [119]:
mnames = ['movie_id', 'title', 'genres']

In [120]:
movies = pd.read_csv('../ml/movies.csv')

In [121]:
movies[:10]

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   
5        6                         Heat (1995)   
6        7                      Sabrina (1995)   
7        8                 Tom and Huck (1995)   
8        9                 Sudden Death (1995)   
9       10                    GoldenEye (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy  
5                        Action|Crime|Thriller  
6                               Comedy|Romance  
7                           Adventure|Children  
8                                       Action  
9                    Action|Adventure|Thriller

In [122]:
all_genres = []

In [123]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [124]:
genres = pd.unique(all_genres)

In [125]:
genres

array(['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Mystery', 'Sci-Fi', 'IMAX', 'Documentary', 'War', 'Musical',
       'Western', 'Film-Noir', '(no genres listed)'], dtype=object)

In [126]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [127]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [128]:
gen = movies.genres[0]

In [129]:
gen.split('|')

['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy']

In [131]:
dummies.columns.get_indexer(gen.split("|"))

array([0, 1, 2, 3, 4])

In [133]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [134]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))

In [135]:
movies_windic.iloc[0]

movieId                                                               1
title                                                  Toy Story (1995)
genres                      Adventure|Animation|Children|Comedy|Fantasy
Genre_Adventure                                                       1
Genre_Animation                                                       1
Genre_Children                                                        1
Genre_Comedy                                                          1
Genre_Fantasy                                                         1
Genre_Romance                                                         0
Genre_Drama                                                           0
Genre_Action                                                          0
Genre_Crime                                                           0
Genre_Thriller                                                        0
Genre_Horror                                                    

In [136]:
np.random.seed(12345)

In [137]:
values = np.random.rand(10)

In [138]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [139]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [140]:
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [141]:
val = 'a,b, guido'

In [142]:
val.split(',')

['a', 'b', ' guido']

In [151]:
pieces = [x.strip() for x in val.split(',')]

In [152]:
pieces

['a', 'b', 'guido']

In [153]:
first, second, third = pieces

In [154]:
first + '::' + second + '::' + third

'a::b::guido'

In [155]:
'::'.join(pieces)

'a::b::guido'

In [156]:
'guido' in val

True

In [157]:
val.index(',')

1

In [158]:
val.find(':')

-1

In [159]:
val.index(':')

ValueError: substring not found

In [160]:
val.count(',')

2

In [161]:
val.replace(',', '::')

'a::b:: guido'

In [162]:
val.replace(',', '')

'ab guido'